### ISSUE TITLE
Wrong type of `e1 << e2`

### ISSUE THREAD

**Issue by rillig** [splintchecker/splint#13]
https://stackoverflow.com/questions/55673029/does-a-c-shift-expression-have-unsigned-type

> It's a bug in Splint. Splint wrongly assumes that the type of `e1 << e2` is `ctype_wider(te1, te2)`. The correct type would be just `te1`.
>
> The [buggy code starts here](https://github.com/ravenexp/splint/blob/d8b2a2466a35bd225794e598df9c665ea6727dae/src/exprNode.c#L5676) by using the same code path for the bitwise operators like `&`, `|` and `^`, as well as for the `<<` and `>>` operators.
>
> The [actual bug is at the end of that code](https://github.com/ravenexp/splint/blob/d8b2a2466a35bd225794e598df9c665ea6727dae/src/exprNode.c#L5775), which assumes that for all these bitwise binary operators, the return type is `ctype_wider(te1, te2)`.

**Comment by bpringlemeir** [comment]
Fixed by 5201227f3eb70887df10b13c6bea3049a228d2ca
