### ISSUE TITLE
Compile error 

### ISSUE THREAD

**Issue by ubuntu-repo** [splintchecker/splint#14]
`make  all-recursive
make[1]: Map '/home/rob/Source/github/splint' wordt binnengegaan
Making all in src
make[2]: Map '/home/rob/Source/github/splint/src' wordt binnengegaan
Compiling cgrammar.c...
cgrammar.c: In function ‘yyparse’:
cgrammar.c:4651:90: error: expected ‘;’ before ‘}’ token
     { DPRINTF ((message("Empty optSpecClauseList") )); (yyval.srset) = sRefSet_undefined }
                                                                                          ^
cgrammar.c:4886:27: error: expected ‘;’ before ‘}’ token
     {context_enterSizeof()}
                           ^
cgrammar.c:4892:27: error: expected ‘;’ before ‘}’ token
     {context_leaveSizeof()}
                           ^
Makefile:1256: recipe for target 'cgrammar.o' failed
make[2]: *** [cgrammar.o] Error 1
make[2]: Map '/home/rob/Source/github/splint/src' wordt verlaten
Makefile:393: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Map '/home/rob/Source/github/splint' wordt verlaten
Makefile:334: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by tzpeng** [comment]
sudo apt install flex
echo "int yywrap() { return 1; }" >> src/cscanner.c

**Comment by bpringlemeir** [comment]
This issue is fixed on the current master.  See commit id fee257b6ec2fc92174599fddff2f6f99ace72c61.
