### ISSUE TITLE
Can I exclude reports from a supplied header?

### ISSUE THREAD

**Issue by volkers** [splintchecker/splint#18]
Hi,
I couldn't find a mailing list so I ask my question here. Sorry, if this would not be appropriate.
In my embedded project I have a bunch of header files supplied by the tool chain. When I run splint on my part of the code, it produces a lot of warnings about issues in these library headers and it is hard to find the issues in my own files. How could I suppress all reports for certain files? (I don't want to edit these files, just ignore issues inside).

Thanks and regards
Volker

**Comment by evansuva** [comment]
You may be able to do what you want by using the `sysdirs` flag. See p. 67-68 of http://splint.org/downloads/manual.pdf.

**Comment by volkers** [comment]
Thanks, that flag changed a lot! I got a lot of new problems but I hope I'm on the right track.
Regards
Volker
