### ISSUE TITLE
Support standard type 'bool'

### ISSUE THREAD

**Issue by ascherer** [splintchecker/splint#27]
After [my code](https://github.com/ascherer/cweb/blob/master/common.c) declares
```
#include <stdbool.h>
...
typedef bool boolean;
```

`splint common.c` complains
```
common.h:36:14: Type boolean is probably meant as a boolean type, but the
    boolean type name is not set. Use -booltype boolean to set it.
  Use the -booltype, -boolfalse and -booltrue flags to change the name of the
  default boolean type. (Use -likelybool to inhibit warning)
```

and `splint -booltype boolean common.c` complains
```
common.h:36:14: Boolean type boolean defined using non-standard type bool
                   (integral, char or enum type expected)
```

Please add support for “non-standard standard type **bool**”.

**Comment by ascherer** [comment]
Note to self: This may be a user error, fixable by setting some command-line flags. `stdbool.h` seems to be used in `splint` already.

**Comment by cooljeanius** [comment]
This kinda ties in with bug #12
