### ISSUE TITLE
splint gives 'Parse Error' on binary constants

### ISSUE THREAD

**Issue by astoutkenwood** [splintchecker/splint#5]
Source file contains:

    #define Temp_KEY                0b0000000000000001
    if(g_KeyInfo.CurKey!=Temp_KEY)

Hex values are supported, so supporting binary constants should be straightforward.

**Comment by bpringlemeir** [comment]
It is not so easy as you may think.  I might look into it.  Patches welcome.

**Comment by bpringlemeir** [comment]
Can you please verify this works on your code?
